### ISSUE TITLE
Docker image cannot be directly imported

### ISSUE THREAD

**Issue by avandecreme** [openbao/openbao#261]
**Describe the bug**
I was trying to import the docker image of the alpha release with this command:
```
docker import https://github.com/openbao/openbao/releases/download/v2.0.0-alpha20240329/openbao_ubi_linux_amd64_2.0.0-alpha20240329_f20d4684d48c8f841025a50c3cb54aa12434e8e0.docker.tar.zip
```
But I get:
```
Downloading from https://github.com/openbao/openbao/releases/download/v2.0.0-alpha20240329/openbao_ubi_linux_amd64_2.0.0-alpha20240329_f20d4684d48c8f841025a50c3cb54aa12434e8e0.docker.tar.zip
archive/tar: invalid tar header
```

I was able to workaround the issue by downloading the zip file, extracting it locally and then running:
```
sudo tar -c . | docker import - openbao_ubi_linux_amd64_2.0.0-alpha20240329_f20d4684d48c8f841025a50c3cb54aa12434e8e0.docker
```
As documented here: https://docs.docker.com/reference/cli/docker/image/import/#import-from-a-local-directory

I suspect that docker doesn't like `zip` and expect `tar` or `tar.gz` instead.

**To Reproduce**
1. Run
```
docker import https://github.com/openbao/openbao/releases/download/v2.0.0-alpha20240329/openbao_ubi_linux_amd64_2.0.0-alpha20240329_f20d4684d48c8f841025a50c3cb54aa12434e8e0.docker.tar.zip
```

**Expected behavior**
docker should be able to import the image directly

**Environment:**
* Server Operating System/Architecture: both linux amd64 and mac M1 with colima are affected

**Comment by cipherboy** [comment]
@avandecreme Note that GitHub actions automatically zips [all artifacts on generation](https://github.com/actions/upload-artifact?tab=readme-ov-file#zip-archives), prior to download.  This does not appear to be controllable on our end.

I suspect if you were to unzip it first, you'd have better results. :-)

p.s., in the past I used `podman load` rather than `podman import`, as the latter did not work for me due to format of the archive.

**Comment by avandecreme** [comment]
Ho, didn't know that. Closing then.

**Comment by cipherboy** [comment]
@avandecreme I think its valid to discuss; I suspect @naphelps wanted to keep the images from the existing `build` pipeline stage as-is, so that we don't get questions of why the checksums are different and have to explain the unzipping. :-)

I think perhaps the alternative build pipeline discussed in #239 and updated in #259 will help clean this up.

**Comment by naphelps** [comment]
@avandecreme Yeah the goal with this release was to keep things a bit more compatible with upstream out of the gate. Our next release should have the docker images in proper registries for consumption.

**Comment by avandecreme** [comment]
Indeed it works with your instructions. Thank you very much!
