### ISSUE TITLE
docs: SEO tags on openbao.org incorrect

### ISSUE THREAD

**Issue by joewxboy** [openbao/openbao#283]
**Describe the bug**
When I share openbao.org on LinkedIn, the thumbnail is blank and the words below say "porkbun.com parked domain".

**To Reproduce**
1. Begin a post on LinkedIn
2. type in openbao.org and hit enter (but don't post yet)
3. view the preview below

**Expected behavior**
You should see a graphic representing OpenBao and a short text description describing the project.

**Environment:**
* web browsers

**Comment by cipherboy** [comment]
AFAICT, the phrase `porkbun` does not include in our source tree. I suspect what has happened is at one point, someone accessed `openbao.org` earlier in the domain's lifetime from LinkedIn, and it has subsequently been cached, which is what you're getting (rather than a fresh preview with our website). My 2c, but I'm not sure there's much we can do. 

See also: https://github.com/search?q=org%3Aopenbao+porkbun&type=code

**Comment by JanMa** [comment]
Can't confirm this anymore. Closing this as this works fine for me now
