### ISSUE TITLE
404 page for Kubernetes Helm instructions

### ISSUE THREAD

**Issue by youvegotmoxie** [openbao/openbao#303]
The installation documentation for Kubernetes is a dead link: https://openbao.org/docs/platform/k8s/helm/

**Comment by cipherboy** [comment]
Ah, I think this needs to be removed, it wasn't forked per #40 was my understanding. Mind opening a PR? Thank you!

**Comment by youvegotmoxie** [comment]
Sure thing

**Comment by cipherboy** [comment]
Ah, my bad. They were forked but not yet rebranded. I think what probably needs to happen (ideally) is the forked projects are cleaned up and then the docs are re-added and updated accordingly.

**Comment by JanMa** [comment]
The K8s docs are not displayed on the main website for now because they still are a work in progress. Also the whole ecosystem of repositories which are needed for proper K8S support are forked but for far nobody has hat the time to work on them. That's why I've marked the relevant documentation pages as a draft some time ago. If you start a local development build of our docs, they are visible.
See for example :
https://github.com/openbao/openbao/blob/main/website/content/docs/platform/k8s/index.mdx?plain=1#L2
